"""Cognitive state orchestration for MPJRD neurons."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Dict


class NetworkState(Enum):
    """Operational macro-state for learning and consolidation."""

    ACTIVE = "active"
    FOCUSED_LEARNING = "focused_learning"
    SLEEP_CONSOLIDATION = "sleep_consolidation"
    MEMORY_REPLAY = "memory_replay"
    HOMEOSTATIC_RECOVERY = "homeostatic_recovery"


@dataclass(frozen=True)
class NeuromodulatoryState:
    """Continuous neuromodulatory latent state.

    Parameters
    ----------
    dopamine_like_signal : float
        Reward/saliency signal in ``[0, 1]``.
    acetylcholine_like_signal : float
        Attention/novelty signal in ``[0, 1]``.
    norepinephrine_like_signal : float
        Alert/surprise signal in ``[0, 1]``.
    serotonin_like_signal : float
        Stabilization signal in ``[0, 1]``.
    """

    dopamine_like_signal: float
    acetylcholine_like_signal: float
    norepinephrine_like_signal: float
    serotonin_like_signal: float


@dataclass(frozen=True)
class OrientationPolicy:
    """Policy generated by the orientation controller."""

    current_mode: NetworkState
    effective_eta: float
    effective_attention_gain: float
    effective_competition_gain: float
    effective_replay_priority: float
    effective_consolidation_rate: float
    effective_decay_rate: float
    sensory_excitability: float


class NetworkOrientationController:
    """Compute network state transitions and effective learning gates."""

    def __init__(self, base_eta: float, replay_interval_steps: int = 32):
        self.base_eta = float(base_eta)
        self.replay_interval_steps = max(1, int(replay_interval_steps))

    @staticmethod
    def _clip(value: float, low: float = 0.0, high: float = 1.0) -> float:
        return max(low, min(high, float(value)))

    def compute_neuromodulators(
        self,
        reward_signal: float,
        novelty_estimate: float,
        surprise_estimate: float,
        stability_ratio: float,
    ) -> NeuromodulatoryState:
        """Estimate neuromodulatory tone from local statistics.

        Parameters
        ----------
        reward_signal : float
            External or endogenous reward signal in ``[-1, 1]``.
        novelty_estimate : float
            Novelty estimate in ``[0, 1]``.
        surprise_estimate : float
            Surprise/error estimate in ``[0, 1]``.
        stability_ratio : float
            Homeostatic stability estimate in ``[0, 1]``.

        Returns
        -------
        NeuromodulatoryState
            Estimated neuromodulatory state.
        """

        dopamine = self._clip(0.5 + 0.5 * reward_signal)
        acetylcholine = self._clip(0.5 * novelty_estimate + 0.5 * surprise_estimate)
        norepinephrine = self._clip(0.6 * surprise_estimate + 0.4 * novelty_estimate)
        serotonin = self._clip(stability_ratio)
        return NeuromodulatoryState(
            dopamine_like_signal=dopamine,
            acetylcholine_like_signal=acetylcholine,
            norepinephrine_like_signal=norepinephrine,
            serotonin_like_signal=serotonin,
        )

    def determine_operational_mode(
        self,
        current_state: NetworkState,
        circadian_encoding_gate: float,
        circadian_consolidation_gate: float,
        pending_eligibility_mass: float,
        saturation_ratio: float,
        stability_ratio: float,
        novelty_estimate: float,
        step_index: int,
    ) -> NetworkState:
        """Select operational state based on endogenous network pressure."""

        if saturation_ratio > 0.85 or stability_ratio < 0.3:
            return NetworkState.HOMEOSTATIC_RECOVERY
        if circadian_consolidation_gate > 0.6 and pending_eligibility_mass > 0.05:
            return NetworkState.SLEEP_CONSOLIDATION
        if (
            circadian_consolidation_gate > 0.45
            and step_index % self.replay_interval_steps == 0
            and pending_eligibility_mass > 0.02
        ):
            return NetworkState.MEMORY_REPLAY
        if circadian_encoding_gate > 0.6 and novelty_estimate > 0.55:
            return NetworkState.FOCUSED_LEARNING
        if current_state == NetworkState.MEMORY_REPLAY and circadian_consolidation_gate > 0.4:
            return NetworkState.SLEEP_CONSOLIDATION
        return NetworkState.ACTIVE

    def compose_policy(
        self,
        state: NetworkState,
        circadian_attention_gate: float,
        circadian_encoding_gate: float,
        circadian_consolidation_gate: float,
        neuromodulatory_state: NeuromodulatoryState,
    ) -> OrientationPolicy:
        """Compose effective gains and rates for current state."""

        dopamine = neuromodulatory_state.dopamine_like_signal
        ach = neuromodulatory_state.acetylcholine_like_signal
        norepi = neuromodulatory_state.norepinephrine_like_signal
        serotonin = neuromodulatory_state.serotonin_like_signal

        eta = self.base_eta * (0.5 + 0.5 * circadian_encoding_gate)
        attention = 0.8 + 0.4 * circadian_attention_gate + 0.3 * ach
        competition = 1.0 + 0.5 * norepi
        replay = (0.3 + 0.7 * dopamine) * circadian_consolidation_gate
        consolidation = (0.2 + 0.8 * dopamine) * circadian_consolidation_gate
        decay = 0.98 + 0.015 * serotonin
        sensory_excitability = 1.0

        if state == NetworkState.FOCUSED_LEARNING:
            eta *= 1.6
            attention *= 1.25
        elif state == NetworkState.SLEEP_CONSOLIDATION:
            eta *= 0.2
            sensory_excitability = 0.45
            consolidation *= 1.35
            decay = min(decay, 0.985)
        elif state == NetworkState.MEMORY_REPLAY:
            eta *= 0.45
            sensory_excitability = 0.6
            replay *= 1.4
        elif state == NetworkState.HOMEOSTATIC_RECOVERY:
            eta *= 0.15
            attention *= 0.6
            competition *= 0.75
            sensory_excitability = 0.7
            decay = min(decay, 0.98)

        return OrientationPolicy(
            current_mode=state,
            effective_eta=eta,
            effective_attention_gain=attention,
            effective_competition_gain=competition,
            effective_replay_priority=replay,
            effective_consolidation_rate=consolidation,
            effective_decay_rate=decay,
            sensory_excitability=sensory_excitability,
        )


def state_transition_event(old_state: NetworkState, new_state: NetworkState, step_id: int) -> Dict[str, float | str | int]:
    """Build a standardized state transition event payload."""

    return {
        "event": "network_state_transition",
        "step_id": int(step_id),
        "old_state": old_state.value,
        "new_state": new_state.value,
    }
